export const blogs = [
  {
    id: 1,
    slug: "bmi-calculator-guide",
    title: "BMI Calculator Guide",
    image: "/Blogs/bmi.webp",
    description: "Learn everything about BMI Calculator.",
    date: "July 25, 2026",
    category: "Calculator",
  },
  {
    id: 2,
    slug: "age-calculator-guide",
    title: "Age Calculator Guide",
    image: "/blogs/age.webp",
    description: "Calculate your exact age instantly.",
    date: "July 26, 2026",
    category: "Calculator",
  },
  {
    id: 3,
    slug: "percentage-calculator-guide",
    title: "Percentage Calculator Guide",
    image: "/blogs/percentage.webp",
    description: "Learn how to calculate percentages easily.",
    date: "July 27, 2026",
    category: "Calculator",
  },
  {
    id: 4,
    slug: "word-counter-guide",
    title: "Word Counter Guide",
    image: "/blogs/word-counter.webp",
    description: "Count words, characters, and paragraphs instantly.",
    date: "July 28, 2026",
    category: "Utility",
  },
  {
    id: 5,
    slug: "password-generator-guide",
    title: "Password Generator Guide",
    image: "/blogs/password.webp",
    description: "Create strong and secure passwords online.",
    date: "July 29, 2026",
    category: "Utility",
  },
  {
    id: 6,
    slug: "qr-code-generator-guide",
    title: "QR Code Generator Guide",
    image: "/blogs/qr.webp",
    description: "Generate QR codes for websites, text, and more.",
    date: "July 30, 2026",
    category: "Utility",
  },
  {
    id: 7,
    slug: "image-resizer-guide",
    title: "Image Resizer Guide",
    image: "/blogs/image-resizer.webp",
    description: "Resize images quickly without losing quality.",
    date: "July 31, 2026",
    category: "Image",
  },
  {
    id: 8,
    slug: "image-compressor-guide",
    title: "Image Compressor Guide",
    image: "/blogs/image-compressor.webp",
    description: "Compress images while maintaining quality.",
    date: "August 1, 2026",
    category: "Image",
  },
  {
    id: 9,
    slug: "image-cropper-guide",
    title: "Image Cropper Guide",
    image: "/blogs/image-cropper.webp",
    description: "Crop images to the perfect size online.",
    date: "August 2, 2026",
    category: "Image",
  },
  {
    id: 10,
    slug: "png-to-jpg-guide",
    title: "PNG to JPG Guide",
    image: "/blogs/png-to-jpg.webp",
    description: "Convert PNG images to JPG effortlessly.",
    date: "August 3, 2026",
    category: "Image",
  },
  {
    id: 11,
    slug: "jpg-to-png-guide",
    title: "JPG to PNG Guide",
    image: "/blogs/jpg-to-png.webp",
    description: "Convert JPG images into PNG format.",
    date: "August 4, 2026",
    category: "Image",
  },
  {
    id: 12,
    slug: "image-converter-guide",
    title: "Image Converter Guide",
    image: "/blogs/image-converter.webp",
    description: "Convert images between popular formats.",
    date: "August 5, 2026",
    category: "Image",
  },
  {
    id: 13,
    slug: "pdf-to-word-guide",
    title: "PDF to Word Guide",
    image: "/blogs/pdf-to-word.webp",
    description: "Convert PDF files into editable Word documents.",
    date: "August 6, 2026",
    category: "PDF",
  },
  {
    id: 14,
    slug: "word-to-pdf-guide",
    title: "Word to PDF Guide",
    image: "/blogs/word-to-pdf.webp",
    description: "Convert Word documents into PDF files.",
    date: "August 7, 2026",
    category: "PDF",
  },
  {
    id: 15,
    slug: "pdf-merger-guide",
    title: "PDF Merger Guide",
    image: "/blogs/pdf-merger.webp",
    description: "Merge multiple PDF files into one document.",
    date: "August 8, 2026",
    category: "PDF",
  },
  {
    id: 16,
    slug: "pdf-splitter-guide",
    title: "PDF Splitter Guide",
    image: "/blogs/pdf-splitter.webp",
    description: "Split PDF files into separate pages easily.",
    date: "August 9, 2026",
    category: "PDF",
  },
  {
    id: 17,
    slug: "pdf-to-jpg-guide",
    title: "PDF to JPG Guide",
    image: "/blogs/pdf-to-jpg.webp",
    description: "Convert PDF pages into JPG images.",
    date: "August 10, 2026",
    category: "PDF",
  },
  {
    id: 18,
    slug: "jpg-to-pdf-guide",
    title: "JPG to PDF Guide",
    image: "/blogs/jpg-to-pdf.webp",
    description: "Convert JPG images into PDF documents.",
    date: "August 11, 2026",
    category: "PDF",
  },
  {
    id: 19,
    slug: "json-formatter-guide",
    title: "JSON Formatter Guide",
    image: "/blogs/json-formatter.webp",
    description: "Format and beautify JSON data with ease.",
    date: "August 12, 2026",
    category: "Developer",
  },
  {
    id: 20,
    slug: "json-validator-guide",
    title: "JSON Validator Guide",
    image: "/blogs/json-validator.webp",
    description: "Validate JSON data and fix syntax errors.",
    date: "August 13, 2026",
    category: "Developer",
  },
  {
    id: 21,
    slug: "base64-encoder-guide",
    title: "Base64 Encoder Guide",
    image: "/blogs/base64-encoder.webp",
    description: "Encode text and files into Base64 format.",
    date: "August 14, 2026",
    category: "Developer",
  },
  {
    id: 22,
    slug: "base64-decoder-guide",
    title: "Base64 Decoder Guide",
    image: "/blogs/base64-decoder.webp",
    description: "Decode Base64 strings quickly and accurately.",
    date: "August 15, 2026",
    category: "Developer",
  },
  {
    id: 23,
    slug: "html-minifier-guide",
    title: "HTML Minifier Guide",
    image: "/blogs/html-minifier.webp",
    description: "Minify HTML code for faster website performance.",
    date: "August 16, 2026",
    category: "Developer",
  },
  {
    id: 24,
    slug: "css-minifier-guide",
    title: "CSS Minifier Guide",
    image: "/blogs/css-minifier.webp",
    description: "Reduce CSS file size for better loading speed.",
    date: "August 17, 2026",
    category: "Developer",
  },
  {
    id: 25,
    slug: "javascript-minifier-guide",
    title: "JavaScript Minifier Guide",
    image: "/blogs/javascript-minifier.webp",
    description: "Optimize JavaScript code by minifying it.",
    date: "August 18, 2026",
    category: "Developer",
  },
  {
    id: 26,
    slug: "url-encoder-guide",
    title: "URL Encoder Guide",
    image: "/blogs/url-encoder.webp",
    description: "Encode URLs safely for web applications.",
    date: "August 19, 2026",
    category: "Developer",
  },
  {
    id: 27,
    slug: "url-decoder-guide",
    title: "URL Decoder Guide",
    image: "/blogs/url-decoder.webp",
    description: "Decode encoded URLs into readable text.",
    date: "August 20, 2026",
    category: "Developer",
  },
  {
    id: 28,
    slug: "pdf-tools-guide",
    title: "PDF Tools Guide",
    image: "/blogs/pdf-tools.webp",
    description: "Discover the best online PDF tools for daily tasks.",
    date: "August 21, 2026",
    category: "PDF",
  },
  {
    id: 29,
    slug: "image-tools-guide",
    title: "Image Tools Guide",
    image: "/blogs/image-tools.webp",
    description: "Explore the best online image editing tools.",
    date: "August 22, 2026",
    category: "Image",
  },
  {
    id: 30,
    slug: "developer-tools-guide",
    title: "Developer Tools Guide",
    image: "/blogs/developer-tools.webp",
    description: "Essential online developer tools for coding productivity.",
    date: "August 23, 2026",
    category: "Developer",
  },
];